[phases.setup]
aptPkgs = [
  "ffmpeg",
  "chromium",
  "fonts-liberation",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libcups2",
  "libdrm2",
  "libgbm1",
  "libgtk-3-0",
  "libnspr4",
  "libnss3",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxkbcommon0",
  "libxrandr2"
]

[phases.install]
cmds = [
  "npm ci",
  "ffmpeg -version"
]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
